============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/alex/github/study/lab2
collected 0 items / 1 error

==================================== ERRORS ====================================
__________________________ ERROR collecting tests.py ___________________________
import file mismatch:
imported module 'tests' has this __file__ attribute:
  /home/alex/github/study/lab2/tests
which is not the same as the test file we want to collect:
  /home/alex/github/study/lab2/tests.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== short test summary info ============================
ERROR tests.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.04s ===============================
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/alex/github/study/lab2
collected 0 items / 1 error

==================================== ERRORS ====================================
__________________________ ERROR collecting tests.py ___________________________
import file mismatch:
imported module 'tests' has this __file__ attribute:
  /home/alex/github/study/lab2/tests
which is not the same as the test file we want to collect:
  /home/alex/github/study/lab2/tests.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== short test summary info ============================
ERROR tests.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.04s ===============================
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  02:37:55 PM
Date is:  10-23-2020
Доброї ночі
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  02:37:56 PM
Date is:  10-23-2020
Доброї ночі
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  02:40:33 PM
Date is:  10-23-2020
Доброї ночі
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/alex/github/study/lab2
collected 0 items / 1 error

==================================== ERRORS ====================================
__________________________ ERROR collecting tests.py ___________________________
import file mismatch:
imported module 'tests' has this __file__ attribute:
  /home/alex/github/study/lab2/tests
which is not the same as the test file we want to collect:
  /home/alex/github/study/lab2/tests.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== short test summary info ============================
ERROR tests.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.04s ===============================
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  02:42:00 PM
Date is:  10-23-2020
Доброї ночі
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/alex/github/study/lab2
collected 4 items

tests/tests.py ..F.                                                      [100%]

=================================== FAILURES ===================================
___________________________ TestClass.test_home_work ___________________________

self = <tests.tests.TestClass testMethod=test_home_work>

    def test_home_work(self):
        # Ваш захист
>       self.assertEqual(home_work(self.date_url), "Добрий день", "Доброї ночі")
E       AssertionError: 'Доброї ночі' != 'Добрий день'
E       - Доброї ночі
E       + Добрий день
E        : Доброї ночі

tests/tests.py:25: AssertionError
=========================== short test summary info ============================
FAILED tests/tests.py::TestClass::test_home_work - AssertionError: 'Доброї но...
========================= 1 failed, 3 passed in 0.81s ==========================
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  02:42:48 PM
Date is:  10-23-2020
Доброї ночі
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  02:51:57 PM
Date is:  10-23-2020
Доброї ночі
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  02:52:39 PM
Date is:  10-23-2020
Доброї ночі
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/alex/github/study/lab2
collected 4 items

tests/tests.py ..F.                                                      [100%]

=================================== FAILURES ===================================
___________________________ TestClass.test_home_work ___________________________

self = <tests.tests.TestClass testMethod=test_home_work>

    def test_home_work(self):
        # Ваш захист
>       self.assertEqual(home_work(self.date_url), "Добрий день", "Доброї ночі")
E       AssertionError: 'Доброї ночі' != 'Добрий день'
E       - Доброї ночі
E       + Добрий день
E        : Доброї ночі

tests/tests.py:25: AssertionError
=========================== short test summary info ============================
FAILED tests/tests.py::TestClass::test_home_work - AssertionError: 'Доброї но...
========================= 1 failed, 3 passed in 0.81s ==========================
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  02:54:45 PM
Date is:  10-23-2020
Доброї ночі
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/alex/github/study/lab2
collected 4 items

tests/tests.py ..F.                                                      [100%]

=================================== FAILURES ===================================
___________________________ TestClass.test_home_work ___________________________

self = <tests.tests.TestClass testMethod=test_home_work>

    def test_home_work(self):
        # Ваш захист
>       self.assertEqual(home_work(self.date_url), "Добрий день", "Доброї ночі")
E       AssertionError: 'Доброї ночі' != 'Добрий день'
E       - Доброї ночі
E       + Добрий день
E        : Доброї ночі

tests/tests.py:25: AssertionError
=========================== short test summary info ============================
FAILED tests/tests.py::TestClass::test_home_work - AssertionError: 'Доброї но...
========================= 1 failed, 3 passed in 0.83s ==========================
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  03:05:25 PM
Date is:  10-23-2020
Доброї ночі
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/alex/github/study/lab2
collected 4 items

tests/tests.py ..F.                                                      [100%]

=================================== FAILURES ===================================
___________________________ TestClass.test_home_work ___________________________

self = <tests.tests.TestClass testMethod=test_home_work>

    def test_home_work(self):
        # Ваш захист
>       self.assertEqual(home_work(self.date_url), "Добрий день", "Доброї ночі")
E       AssertionError: True != 'Добрий день' : Доброї ночі

tests/tests.py:25: AssertionError
----------------------------- Captured stdout call -----------------------------
Доброї ночі
=========================== short test summary info ============================
FAILED tests/tests.py::TestClass::test_home_work - AssertionError: True != 'Д...
========================= 1 failed, 3 passed in 0.76s ==========================
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/alex/github/study/lab2
collected 4 items

tests/tests.py ....                                                      [100%]

============================== 4 passed in 0.82s ===============================
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  03:54:31 PM
Date is:  10-23-2020
Доброї ночі
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/alex/github/study/lab2
collected 4 items

tests/tests.py ....                                                      [100%]

============================== 4 passed in 0.82s ===============================
